### ISSUE TITLE
Typo on line 118?

### ISSUE THREAD

**Issue by TallFrodo** [janegilring/PSCommunity#5] opened 2018-08-06 05:15 UTC
Not sure if I'm just misinterpreting what it's trying to do but I think Line 118 of SetOutlookSignature:
` $SigPath = "\Microsoft\Signaturer\"`

Is meant to be 
` $SigPath = "\Microsoft\Signatures\"`

in order to match up with the default appdata\roaming\microsoft\Signatures\ folder user for outlook sigs. Unless you're intentionally generating it to a different folder and moving it back later in which case feel free to close this off.

**Comment by janegilring** [comment] 2018-11-28 12:11
Sorry for not noticing this issue until now. I believe the script was developed for use on computers with a Norwegian locale, so there is a need to generalize the code to work with other languages.
I'll leave the issue open for now, as I haven`t had a chance to work on the Outlook signature script for a while.

**Comment by janegilring** [comment] 2019-03-25 16:11
As I likely won't get a chance to work any further on this script, I`ll go ahead and close this issue with a "by design" label as it was only tested on computers with a Norwegian locale.

**Closed as completed by janegilring** 2019-03-25 16:11 UTC
